#服务器配置
server:
  port: ${PORT:3011}
  tomcat:
    max-http-form-post-size: 50MB

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: wuji
    password: 123456

      #日志配置
      logging:
        file:
          path: C:/myWork/workspace/myDemoLog/myapp.log