#服务器配置
server:
  port: ${PORT:3011}
  tomcat:
    max-http-form-post-size: 50MB

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: wuji
    password: 123456

    #redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    pool:
      #连接池最大数据库连接数，设为0表示无限制
      max-active: 5
      #连接池最大阻塞等待时间ms，设为-1表示无限等待
      max-wait: 10000
      #连接池最大空闲连接数，设为0表示无限制
      max-idle: 10
      min-idle: 0
    #连接超时时间ms
    timeout: 10000
    #默认登录的数据库个数
    database: 1

#日志配置
logging:
  file:
    path: C:/myWork/workspace/myDemoLog/myapp.log